# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'Cantar intervalo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cantar intervalo
	pod 'Pitchy'
	pod 'Charts', '~> 3.1.1'
	pod 'iOSDropDown'
end
